export const users = [
  { name: "John Doe", email: "john.doe@gmail.com", id: 1, type: "admin" },
  { name: "Jeanne Doe", email: "jeanne.doe@gmail.com", id: 2, type: "staff" },
  { name: "Jean Dupond", email: "jean.dupond@gmail.com", id: 3, type: "staff" },
  {
    name: "Kaleb Nunez",
    email: "kaleb.nunez@gmail.com",
    id: 4,
    type: "member",
  },
  {
    name: "Eloise Rodriguez",
    email: "eloise.rodriguez@gmail.com",
    id: 5,
    type: "member",
  },
  {
    name: "Arman Horton",
    email: "arman.horton@gmail.com",
    id: 6,
    type: "member",
  },
  {
    name: "Bilal Levine",
    email: "bilal.levine@gmail.com",
    id: 7,
    type: "member",
  },
  {
    name: "Maggie Freeman",
    email: "maggie.freeman@gmail.com",
    id: 8,
    type: "member",
  },
  {
    name: "Brandon Silva",
    email: "brandon.silva@gmail.com",
    id: 9,
    type: "member",
  },
  {
    name: "Tamara Small",
    email: "tamara.small@gmail.com",
    id: 10,
    type: "member",
  },
  {
    name: "Maria Walters",
    email: "maria.walters@gmail.com",
    id: 11,
    type: "admin",
  },
  {
    name: "Mason Santos",
    email: "mason.santos@gmail.com",
    id: 12,
    type: "member",
  },
  {
    name: "Ryan O'Connor",
    email: "ryan.oconnor@gmail.com",
    id: 13,
    type: "member",
  },
  {
    name: "Gladys Crawford",
    email: "gladys.crawford@gmail.com",
    id: 14,
    type: "staff",
  },
  {
    name: "Joanne Contreras",
    email: "joanne.contreras@gmail.com",
    id: 15,
    type: "member",
  },
  {
    name: "Luke Jarvis",
    email: "luke.jarvis@gmail.com",
    id: 16,
    type: "staff",
  },
  {
    name: "Yasmine Mcneil",
    email: "yasmine.mcneil@gmail.com",
    id: 17,
    type: "member",
  },
  {
    name: "Estelle Burke",
    email: "estelle.burke@gmail.com",
    id: 18,
    type: "admin",
  },
  {
    name: "Kieron Bass",
    email: "kieron.bass@gmail.com",
    id: 19,
    type: "member",
  },
  {
    name: "Glenn Horton",
    email: "glenn.horton@gmail.com",
    id: 20,
    type: "member",
  },
  {
    name: "Arman Lucero",
    email: "arman.lucero@gmail.com",
    id: 21,
    type: "member",
  },
  {
    name: "Gerard Mclaughlin",
    email: "gerard.mclaughlin@gmail.com",
    id: 22,
    type: "staff",
  },
];
